# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: vs2017-win2016

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.caproj'
  displayName: 'Restore dotnet core'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--no-restore'
  displayName: 'Build Project'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Test.csproj'
  displayName: 'Run Test cases' 

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false 
    projects: '**/CustomerApi.csproj'
    arguments: '--configuration $(BuildConfiguration)  --no-restore'
    modifyOutputPath: false 
  displayName: 'Publish Artifacts'
