# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# single stage single job dotnet core api pipeline

name: NetCoreMicroserviceCiCd
trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
    displayName: 'Restore Dotnet Package'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--no-restore'
    displayName: 'Build Project'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Test.csproj'
      arguments: '--no-restore'
    displayName: 'Run Unit Test'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      arguments: '--configuration $(buildConfiguration) --no-restore'
      projects: '**/CustomerApi.csproj'
      modifyOutputPath: false 
    displayName: 'Publish CustomerAPI'

