# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# single stage single job dotnet core api pipeline

name: NetCoreMicroserviceCiCd
trigger:
- master

# pool:
#   vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

parameters:
  - name: image 
    displayName: Pool Image 
    type: string 
    default: ubuntu-latest 
    values:
    - windows-latest
    - ubuntu-latest 
    - macOS-latest

jobs:
- build 
  displayName: build 
  pool:
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo "hello world"

