# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-18.04

variables:
  buildConfiguration: 'Release'

stages:
- stage: build
  displayName: 'Build Nuget Package'
  jobs:
    - job: 'CI Build'
      displayName: 'Build Nuget Package'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
        displayName: 'Restore Package'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--no-restore'
        displayName: 'Build Project' 

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '**/*Test.csproj'
          arguments: '--no-restore'
        displayName: 'Test'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/CustomerApi.csproj'
          arguments: '--configuration $(buildconfiguration) --no-restore'
          modifyOutputPath: false
        displayName: 'publish customer API'
- stage: Deploy
  dependsOn: build
  displayName: 'publish package'
  environment: nuget-publish
  